# Generated by Django 2.2.6 on 2020-01-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pud_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
